SELECT EMP_CGC CNPJ
, UPPER(EMP_RAZ_SOC) RAZAO_SOCIAL
, UPPER(FND_OBS) DOCUMENTO
, CONVERT(VARCHAR, FND_DT_VALID, 103) DATA_VALIDADE
FROM EMP, FND
WHERE EMP_FNE_COD = FND_FNE_COD
AND EMP_STATUS = 'A'
ORDER BY EMP_CGC, FND_DT_VALID