SELECT A.NR_SEQUENCIA SEQUENCIA
    , A.DT_BAIXA DATA_LIQUIDACAO
    , A.DT_TRANSACAO DATA_TRANSACAO
    , A.VL_TRANSACAO VALOR_TRANSACAO
    , DECODE(A.IE_TIPO_CARTAO, 'C', 'CRÉDITO', 'D', 'DÉBITO') TIPO_CARTAO
    , A.QT_PARCELA PARCELAS
    , UPPER(A.NM_USUARIO_NREC) USUARIO_CAIXA
    , UPPER(B.DS_BANDEIRA) BANDEIRA
    , UPPER(C.DS_FORMA_PAGTO) FORMA_PAGAMENTO
    , UPPER(D.NM_FANTASIA_ESTAB) ESTABELECIMENTO
    --, A.VL_DESPESA VALOR_DESPESA
    --, (A.VL_TRANSACAO - A.VL_DESPESA) VALOR_LIQUIDO
FROM MOVTO_CARTAO_CR A
    INNER JOIN BANDEIRA_CARTAO_CR B
        ON A.NR_SEQ_BANDEIRA = B.NR_SEQUENCIA
    INNER JOIN FORMA_PAGTO_CARTAO_CR C
        ON A.NR_SEQ_FORMA_PAGTO = C.NR_SEQUENCIA
    INNER JOIN ESTABELECIMENTO D
        ON A.CD_ESTABELECIMENTO = D.CD_ESTABELECIMENTO
WHERE A.IE_SITUACAO = 'A'
AND A.DT_TRANSACAO >= INICIO_DIA('08/07/2019') 
AND A.DT_TRANSACAO <= FIM_DIA('08/07/2019')  
AND B.IE_SITUACAO = 'A'
AND C.IE_SITUACAO = 'A'
AND D.IE_SITUACAO = 'A'

SELECT *
FROM MOVTO_CARTAO_CR A
WHERE A.IE_SITUACAO = 'A'
AND A.DT_TRANSACAO >= INICIO_DIA('08/07/2019') 
AND A.DT_TRANSACAO <= FIM_DIA('08/07/2019')  


SELECT *
FROM BANDEIRA_CARTAO_CR B
WHERE B.IE_SITUACAO = 'A'

SELECT *
FROM FORMA_PAGTO_CARTAO_CR C
WHERE C.IE_SITUACAO = 'A'

SELECT *
FROM ESTABELECIMENTO D
WHERE D.IE_SITUACAO = 'A'

SELECT *
FROM MOVTO_CARTAO_CR_PARCELA E
WHERE NR_SEQ_MOVTO = 12889
--WHERE ROWNUM < 10