
create function TASY.UNIMED_TOT_BACK_CLASS
(IE_DADO VARCHAR2, IE_CLASSIFICACAO_P VARCHAR2)
RETURN NUMBER IS

DS_RETORNO_W NUMBER (8,0);
QT_CLASSIFICACAO_W NUMBER (8,0);
QT_SUBCLASSIFICACAO_W NUMBER (8,0);

BEGIN

if 	(IE_DADO = 'C') then

SELECT decode(count(A.QT_TOTAL),0,1,count(A.QT_TOTAL))
      INTO DS_RETORNO_W
FROM UNIMED_INDICADOR_OS_TI A
WHERE 1 = 1
AND A.IE_STATUS_ORDEM <> 3
AND TRUNC(A.DT_ORDEM_SERVICO,'MM') <= ADD_MONTHS(TRUNC(SYSDATE,'MM'),-1);

ELSIF (IE_DADO = 'SC') THEN

SELECT decode(count(A.QT_TOTAL),0,1,count(A.QT_TOTAL))
       INTO DS_RETORNO_W
FROM UNIMED_INDICADOR_OS_TI A
WHERE 1 = 1
AND A.IE_STATUS_ORDEM <> 3
AND TRUNC(A.DT_ORDEM_SERVICO,'MM') <= ADD_MONTHS(TRUNC(SYSDATE,'MM'),-1)
AND ((upper(A.DS_CLASSIFICACAO) = upper(IE_CLASSIFICACAO_P)) or (upper(IE_CLASSIFICACAO_P) = 'TOTAL'));

END IF;

return	ds_retorno_w;

END UNIMED_TOT_BACK_CLASS;

