# Pre reqs: add Az.CognitiveServices module (run as administrator)
Install-Module Az

# Authentication
$user = 'adm-sergio.queiroz@opty.com.br'
$password = 'Yobx6L2E'
$tenantId = '2e1f754b-dd51-4149-84c0-a9f71b7b2732'
$passwd = ConvertTo-SecureString $user -AsPlainText -Force
$pscredential = New-Object System.Management.Automation.PSCredential($user, $passwd)
Connect-AzAccount -ServicePrincipal -Credential $pscredential -TenantId $tenantId

# See if any Azure Cognitive Services account exists in subscription
Get-AzCognitiveServicesAccount

# List types of API ACS accounts
Get-AzCognitiveServicesAccountType
Get-AzCognitiveServicesAccountSkus -Type SpeechServices -Location EastUS

# Creates a free account
New-AzCognitiveServicesAccount -ResourceGroupName GatewayPowerBI -Name TestAccount -Type SpeechServices -SkuName F0 -Location EastUS

# Full list of available commands
Get-Command -Module Az.CognitiveServices

# Getting a token (necessary only 1st key to authenticate)
$keys = Get-AzCognitiveServicesAccountKey -ResourceGroupName GatewayPowerBI -Name TestAccount
$keys

$headers = @{
    'Ocp-Apim-Subscription-Key' = $keys.Key1
    'Content-Length' = '0'
}

$params = @{
    'Uri' = 'https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken'
    'ContentType' = 'application/x-www-form-urlencoded'
    'Headers' = $headers
    'Method' = 'POST'
}

$token = Invoke-RestMethod @params
$token

# Listing available voices from AZ region
$headers = @{
    'Authorization' = 'Bearer $token'
}

$params = @{
    'Headers' = $headers
    'Method' = 'GET'
    'Uri' = 'https://eastus.tts.speech.microsoft.com/cognitiveservices/voices/list'
}

Invoke-RestMethod @params

# Convert text to speech
$audioOutput = 'audio-16khz-64kbitrate-mono-mp3'
$voiceAgent = 'JessaNeural'
$outputFile = 'C:\Users\sergio.queiroz\OneDrive - Opty\PowerShell-Library\Azure\Convert-TextSpeech.mp3'
$gender = 'Female'
$text = "Hello, you're listening an audio generated by Azure Cognitive Services"
$ssml = @'

{2}

'@ -f $gender, $voiceAgent, $text

$params = @{
    Headers = @{
        'X-Microsoft-OutputFormat' = $audioOutput
        'Authorization' = "Bearer $token"
    }
    'ContentType' = 'appliacation/ssml+xml'
    'Body' = $ssml
    'Method' = 'POST'
    'URI' = 'https://eastus.tts.speech.microsoft.com/cognitiveservices/v1'
    'OutFile' = $outputFile
}
Invoke-RestMethod @params