SELECT CONVERT(VARCHAR, A.fnd_dt_valid,103) DATA_VALIDADE
    , DATEDIFF(DAY, GETDATE(), A.fnd_dt_valid) DIAS_VENCIMENTO
    , UPPER(A.fnd_doc) DOCUMENTO
    , UPPER(A.fnd_obs) OBSERVACAO_DOCUMENTO
    , SUBSTRING(B.EMP_CGC, 1,2) + '.' + SUBSTRING(B.EMP_CGC,3,3) + '.' + SUBSTRING(B.EMP_CGC,6,3) + '/' + SUBSTRING(B.EMP_CGC,9,4) + '-' + SUBSTRING(B.EMP_CGC,13,2) CNPJ
    , UPPER(B.EMP_NOME_FANTASIA) EMP_NOME_FANTASIA
    , UPPER(B.EMP_RAZ_SOC) RAZAO_SOCIAL
    , UPPER(B.EMP_CONTATO) CONTATO
    , B.EMP_FONE TELEFONE
    , LOWER(B.EMP_EMAIL) EMAIL
FROM FND A
    INNER JOIN EMP B
        ON A.fnd_fne_cod = B.EMP_FNE_COD
WHERE B.EMP_STATUS = 'A'
ORDER BY A.fnd_dt_valid