SELECT nfs.nfs_serie,
    nfs.nfs_numero,
    nfs.nfs_tipo,
    nfs.nfs_natur_oper,
    nfs.nfs_dt_emis,
    nfs.nfs_dt_vcto,
    nfs.nfs_perc_iss,
    nfs.nfs_perc_ir,
    nfs.nfs_vlr_iss,
    nfs.nfs_vlr_ir,
    nfs.nfs_valor,
    nfs.nfs_perc_multa,
    nfs.nfs_perc_juro,
    nfs.nfs_desconto,
    nfs.nfs_emp_codigo,
    nfs.nfs_status,
    nfs.nfs_str_cod,
    nfs.nfs_bloquete,
    nfs.nfs_descr,
    nfs.nfs_emp_cod,
    nfs.nfs_nde_serie,
    nfs.nfs_nde_tipo,
    nfs.nfs_nde_num,
    nfs.nfs_dt_envio,
    nfs.nfs_usr_login,
    nfs.nfs_justif,
    nfs.nfs_dt_receb,
    nfs.nfs_fluxo_caixa,
    nfs.nfs_ind_duvidoso,
    nfs.nfs_nfl_num,
    nfs.nfs_ns_tipo,
    nfs.nfs_ns_serie,
    nfs.nfs_ns_numero,
    nfs.nfs_remessa,
    nfs.nfs_motivo_reapresentacao,
    nfs.nfs_nfl_serie,
    str.str_nome
FROM nfs,
    str
WHERE (str.str_cod = nfs.nfs_str_cod)
    AND ((nfs.nfs_tipo = 'NR'))
ORDER BY nfs.nfs_dt_emis DESC,
    nfs.nfs_serie ASC,
    nfs.nfs_numero DESC