SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REQUESTIA_CAPEX_OPEX](
	CHAMADO VARCHAR(20) NULL,
	PRODUTO VARCHAR(255) NULL,
	ANO INT NULL,
	MES [VARCHAR](30) NULL,
	MARCA [VARCHAR](300) NULL,
	PACOTE [VARCHAR](300) NULL,
	UNIDADE_ATENDIMENTO [VARCHAR](300) NULL,
	VALOR_CHAMADO [VARCHAR](20) NULL,
	REGIONAL [VARCHAR](300) NULL,
    DT_ABERTURA [VARCHAR](300) NULL,
    DT_FECHAMENTO [VARCHAR](300) NULL,
    CENTRO_CUSTO [VARCHAR](300) NULL,
    FORNECEDOR [VARCHAR](300) NULL
)
------------------------------------------------------------------------------------------
SELECT TOP 10 * FROM REQUESTIA_CAPEX_OPEX
------------------------------------------------------------------------------------------





SELECT  RR.REQUEST AS CHAMADO
        , RR.PRODUCT AS PRODUTO
        , YEAR(RR.RESOLUCAO) AS ANO
        , CASE DATEPART(MONTH, RR.RESOLUCAO) WHEN 1 THEN 'Janeiro' WHEN 2 THEN 'Fevereiro'WHEN 3 THEN 'Março'WHEN 4 THEN 'Abril'WHEN 5 THEN 'Maio'WHEN 6 THEN 'Junho'
            WHEN 7 THEN 'Julho'WHEN 8 THEN 'Agosto'WHEN 9 THEN 'Setembro'WHEN 10 THEN 'Outubro'WHEN 11 THEN 'Novembro'WHEN 12 THEN 'Dezembro'END AS MES
        , R1.QANSWER AS MARCA
        , R2.QANSWER AS PACOTE
        , RR.UNIDADE_ATENDIMENTO AS UNIDADE_ATENDIMENTO
        , R3.QANSWER AS VALOR_CHAMADO
        , RR.REGIONAL AS REGIONAL
        , CONVERT(VARCHAR(10), RR.ABERTURA, 103) AS DT_ABERTURA
        , CONVERT(VARCHAR(10), RR.RESOLUCAO, 103) AS DT_FECHAMENTO
        , R4.CENTRO_CUSTO AS CENTRO_CUSTO
        , R5.QANSWER AS FORNECEDOR
FROM    REQUESTIA_REQUESTS RR
        LEFT JOIN REQUESTIA_QANSWER R1 ON RR.QSESSIONFORM = R1.QSESSION AND R1.QUESTION = 'COM_GER_Com_Marca'
        LEFT JOIN REQUESTIA_QANSWER R2 ON RR.QSESSIONFORM = R2.QSESSION AND R2.QUESTION = 'COM_GER_Com_Pacote'
        LEFT JOIN REQUESTIA_QANSWER R3 ON RR.QSESSIONFORM = R3.QSESSION AND R3.QUESTION = 'COM_GER_Com_Valor'
        LEFT JOIN REQUESTIA_QANSWER R4 ON RR.QSESSIONFORM = R4.QSESSION AND R4.QUESTION = 'GER_CCusto'
        LEFT JOIN REQUESTIA_QANSWER R5 ON RR.QSESSIONFORM = R5.QSESSION AND R5.QUESTION LIKE 'CONTAS_PGTO_For%'        
WHERE   MONTH(RR.RESOLUCAO) = '1'
        AND YEAR(RR.RESOLUCAO) = '2021'
        AND RR.PRODUCT IN ('Contratos','Solicitação de Pagamento','Compras de Servicos','Reembolso de Despesas','Compra de Diversos')
        AND R2.QANSWER IN ('OPEX - TI & Telecom','OPEX - TI & Telecom - Call Center','CAPEX - TI & Telecom')
ORDER BY 1