SELECT  RR.REQUEST AS CHAMADO 
        , CONVERT(VARCHAR(10), RR.ABERTURA, 103) AS DT_ABERTURA
        , CONVERT(VARCHAR(10), RR.ULTIMA_ACAO, 103) AS ULTIMA_ACAO
        , [%_SLA] AS SLA
        , RR.CLIENT AS SOLICITANTE
        , R1.QANSWER AS SETOR
        , RR.ORGUNIT AS UNIDADE_SOLICITANTE
        , RR.UNIDADE_ATENDIMENTO AS UNIDADE_ATENDIMENTO
        , RR.PRODUCT AS PRODUTO
        , RR.PROCESS AS PROCESSO
        , RR.RSTATUS AS STATUS
        , R2.QANSWER AS OS_EXTERNA
        , RR.CURRANAL AS ANALISTA_TI
FROM    REQUESTIA_REQUESTS RR
        INNER JOIN REQUESTIA_QANSWER R1 ON RR.QSESSIONFORM = R1.QSESSION AND R1.QUESTION = 'GER_AreaAtuacao'
        LEFT JOIN REQUESTIA_QANSWER R2 ON RR.QSESSIONFORM = R2.QSESSION AND R2.QUESTION = 'TI_ABERTO_TERCEIRO'
WHERE   RR.CATEGORY = 'Tecnologia da Informação'
        AND RR.RSTATUS NOT IN ('Aguardando Aprovação','Cancelado a Pedido do Cliente','Cancelado Abertura Incorreta','Encerrado','Encerrado','Encerrado - Falta de Retorno','Reprovado')
        AND RR.PRODUCT = 'Philips Tasy'
        AND R2.QANSWER IS NOT NULL
ORDER BY 1 ASC

--SELECT TOP 10 * FROM REQUESTIA_REQUESTS WHERE PRODUCT = 'Philips Tasy'