/* TAXAS E BOLETOS */
SELECT R.REQUEST CHAMADO
    , UPPER(R.PRODUCT) PRODUTO
    , UPPER(R.PROCESS) PROCESSO
    , CONVERT(VARCHAR(10), R.ABERTURA, 103) ABERTURA
    , CONVERT(VARCHAR(10), R.RESOLUCAO, 103) ENCERRAMENTO
    , UPPER(R.RSTATUS) STATUS
    , UPPER(R.CLIENT) SOLICITANTE
    , UPPER(R.CURRANAL) ANALISTA
    , R.MARCA MARCA
    , R.[UNIDADE ATENDIMENTO] UNIDADE
    , R.[SIGLA UNIDADE] SIGLA
    , A1.QANSWER FORNECEDOR
    , A2.QANSWER VALOR
    , CONVERT(VARCHAR(10), CONVERT(DATE, A3.QANSWER, 111), 103) EMISSAO
    , CONVERT(VARCHAR(10), CONVERT(DATE, A4.QANSWER, 111), 103) VENCIMENTO
    , A5.QANSWER OBSERVACAO
INTO dbo.REQUESTIA_PGTOTAXAS
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CONTAS_PGTO_Forn'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CONTAS_PGTO_Valor'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'CONTAS_PGTO_DtaEmi'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CONTAS_PGTO_Venc'
    LEFT JOIN REQUESTIA_QANSWER A5
        ON R.QSESSIONFORM = A5.QSESSION AND A5.QUESTION = 'CONTAS_PGTO_Obs'
WHERE R.CATEGORY = 'Central de Notas'
    AND R.PRODUCT = 'Solicitação de Pagamento'
    AND R.PROCESS = 'Taxas e Boletos'
    AND R.RSTATUS NOT LIKE '%Cancel%'
    --AND R.ABERTURA >= GETDATE()-30
ORDER BY 1 DESC

SELECT *
FROM REQUESTIA_PGTOTAXAS

SELECT *
FROM REQUESTIA_REQUESTS R
WHERE R.QSESSIONFORM = 166712

SELECT A1.*
FROM REQUESTIA_QANSWER A1
WHERE A1.QSESSION = 166712

/* GUIAS */
SELECT R.REQUEST CHAMADO
    , R.QSESSIONFORM
    , UPPER(R.PRODUCT) PRODUTO
    , UPPER(R.PROCESS) PROCESSO
    , CONVERT(VARCHAR(10), R.ABERTURA, 103) ABERTURA
    , CONVERT(VARCHAR(10), R.RESOLUCAO, 103) ENCERRAMENTO
    , UPPER(R.RSTATUS) STATUS
    , UPPER(R.CLIENT) SOLICITANTE
    , UPPER(R.CURRANAL) ANALISTA
    , R.MARCA MARCA
    , R.[UNIDADE ATENDIMENTO] UNIDADE
    , R.[SIGLA UNIDADE] SIGLA
    , A1.QANSWER FORNECEDOR
    , A2.QANSWER VALOR
    , CONVERT(VARCHAR(10), CONVERT(DATE, A3.QANSWER, 111), 103) COMPETENCIA
    , CONVERT(VARCHAR(10), CONVERT(DATE, A4.QANSWER, 111), 103) VENCIMENTO
    , A5.QANSWER OBSERVACAO
INTO dbo.REQUESTIA_PGTOGUIAS
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CONTAS_PGTO_Forn'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CONTAS_PGTO_Valor'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'CP_Impostos_DataComp'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CONTAS_PGTO_Venc'
    LEFT JOIN REQUESTIA_QANSWER A5
        ON R.QSESSIONFORM = A5.QSESSION AND A5.QUESTION = 'CONTAS_PGTO_Obs'
WHERE R.CATEGORY = 'Central de Notas'
    AND R.PRODUCT = 'Solicitação de Pagamento'
    AND R.PROCESS = 'Guias'
    AND R.RSTATUS NOT LIKE '%Cancel%'
    --AND R.ABERTURA >= GETDATE()-30
ORDER BY 1 DESC

SELECT A1.*
FROM REQUESTIA_QANSWER A1
WHERE A1.QSESSION = 166729

SELECT * FROM REQUESTIA_PGTOGUIAS
--DROP TABLE REQUESTIA_PGTOGUIAS

SELECT R.REQUEST CHAMADO
    , UPPER(R.PRODUCT) PRODUTO
    , UPPER(R.PROCESS) PROCESSO
    , CONVERT(VARCHAR(10), R.ABERTURA, 103) ABERTURA
    , UPPER(R.RSTATUS) STATUS
    , CONVERT(VARCHAR(10), R.RESOLUCAO, 103) ENCERRAMENTO
    , UPPER(R.CLIENT) SOLICITANTE
    , UPPER(R.CURRANAL) ANALISTA
    , R.MARCA MARCA
    , R.[UNIDADE ATENDIMENTO] UNIDADE
    , R.[SIGLA UNIDADE] SIGLA
    , A1.QANSWER FORNECEDOR
    , A2.QANSWER VALOR
    , CONVERT(VARCHAR(10), CONVERT(DATE, A3.QANSWER, 111), 103) EMISSAO
    , CONVERT(VARCHAR(10), CONVERT(DATE, A4.QANSWER, 111), 103) VENCIMENTO
    , A5.QANSWER OBSERVACAO
--INTO dbo.REQUESTIA_PGTOTAXAS
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CONTAS_PGTO_Forn'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CONTAS_PGTO_Valor'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'CONTAS_PGTO_DtaEmi'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CONTAS_PGTO_Venc'
    LEFT JOIN REQUESTIA_QANSWER A5
        ON R.QSESSIONFORM = A5.QSESSION AND A5.QUESTION = 'CONTAS_PGTO_Obs'
WHERE R.CATEGORY = 'Central de Notas'

sp_help REQUESTIA_REQUESTS