SELECT R.REQUEST CHAMADO
    , R.[% SLA]
    , R.RSTATUS SITUACAO
    , R.MARCA MARCA
    , R.[UNIDADE ATENDIMENTO]
    , R.[SIGLA UNIDADE]
    , R.ABERTURA ABERTURA
    , R.CLIENT SOLICITANTE
    , R.CURRANAL ANALISTA
    , A1.QANSWER FORNECEDOR
    , A2.QANSWER SERVICO
    , A3.QANSWER [NOTA FISCAL]
    , CONVERT(VARCHAR(10), CONVERT(DATE, A4.QANSWER, 111), 103) [DATA VENCTO]
    , A5.QANSWER VALOR
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CONTAS_PGTO_Forne'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CONTAS_PGTO_DescServProd'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'FAC_Observacao'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CONTAS_PGTO_Vencimento'
    LEFT JOIN REQUESTIA_QANSWER A5
        ON R.QSESSIONFORM = A5.QSESSION AND A5.QUESTION = 'CONTAS_PGTO_Valorr'
WHERE R.CATEGORY = 'Facilities'
AND R.PRODUCT = 'Servicos'
AND R.PROCESS = 'Medição de Contratos'
