SELECT TOP 10 R.QSESSIONFORM, R.*
FROM REQUESTIA_REQUESTS R
WHERE R.RSTATUS = 'Encerrado'
AND R.CATEGORY = 'Central de Cadastros'
AND R.PRODUCT = 'Cadastro Comercial'
AND R.PROCESS LIKE '%TISS%'
AND 
AND R.PRODUCT = 'Reembolso de Despesas'
AND R.CLIENT = 'sergio.queiroz'


SELECT S.*
FROM REQUESTIA_QSESSION S
WHERE S.QSESSION = 12148

SELECT A.* 
FROM REQUESTIA_QANSWER A
WHERE A.QUESTION LIKE '%CAD_PAD_Sist%'
WHERE A.QSESSION = 12148
AND A.QUESTION IN ('CAD_Atualiza_TISS_RazSoc', 'CAD_CLIENTE_CNPJ', 'CAD_CLIENTE_DataSolici', 'CAD_Atualizacao_TISS_Desc', 'CAD_PAD_Sistema')

CSI065237

SELECT R.REQUEST CHAMADO
    , R.MARCA
    , R.[SIGLA UNIDADE] SIGLA
    , R.[UNIDADE ATENDIMENTO] UNIDADE
    , CONVERT(VARCHAR(10), R.ABERTURA, 103) ABERTURA
    , UPPER(R.CLIENT) SOLICITANTE
    , UPPER(R.PROCESS) PROCESSO
    , UPPER(R.RSTATUS) SITUACAO
    , UPPER(R.CURRANAL) ANALISTA
    , FORMAT(R.[% SLA], 'P') SLA
    , CONVERT(VARCHAR(10), R.[ULTIMA ACAO], 103) ULTIMA_ACAO
    , UPPER(A1.QANSWER) CONVENIO
    , CONVERT(VARCHAR(10), CONVERT(DATE, A2.QANSWER, 111), 103) SOLICITACAO
    , UPPER(A3.QANSWER) DESCRICAO
    , UPPER(A4.QANSWER) SISTEMA
INTO REQ_WKF_ATUALIZACAOTISS
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CAD_Atualiza_TISS_RazSoc'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CAD_CLIENTE_DataSolici'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'CAD_Atualizacao_TISS_Desc'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CAD_PAD_Sistema'
WHERE R.CATEGORY = 'Central de Cadastros'
AND R.PRODUCT = 'Cadastro Comercial'
AND R.PROCESS LIKE '%TISS%'

DROP TABLE REQ_WKF_ATUALIZACAOTISS
SELECT * 
FROM REQ_WKF_ATUALIZACAOTISS
ORDER BY 1 DESC