SELECT R.REQUEST CHAMADO
    , R.CLIENT SOLICITANTE
    , R.ABERTURA ABERTURA
    , A1.QANSWER PROJETO
    , A2.QANSWER FORNECEDOR
    , A3.QANSWER OBSERVACAO
    , A4.QANSWER VALOR
    , R.MARCA MARCA
    , R.[UNIDADE ATENDIMENTO]
    , R.[SIGLA UNIDADE]
    , CONVERT(VARCHAR(10), CONVERT(DATE, A5.QANSWER, 111), 103) [DATA EMISSAO]
    , A6.QANSWER NF
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CAP_CAPEX_CC'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CONTAS_PGTO_Forn'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'CONTAS_PGTO_Observacao'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CONTAS_PGTO_Valor'
    LEFT JOIN REQUESTIA_QANSWER A5
        ON R.QSESSIONFORM = A5.QSESSION AND A5.QUESTION = 'CONTAS_PGTO_DataEmis'
    LEFT JOIN REQUESTIA_QANSWER A6
        ON R.QSESSIONFORM = A6.QSESSION AND A6.QUESTION = 'CONTAS_PGTO_NDocumento'
WHERE R.CATEGORY = 'Contas a Pagar'
AND R.PRODUCT = 'Solicitação de CAPEX'
AND R.PROCESS = 'Registro de NFDs'