SELECT FORMAT(R.[TEMPO ULTIMA ACAO (H)] / 8, 'N0') DDU_ULTIMA_ACAO
    , R.REQUEST CHAMADO
    , UPPER(R.CURRANAL) ANALISTA
    , UPPER(R.RSTATUS) STATUS
    , CONVERT(VARCHAR(10), R.ABERTURA, 103) ABERTURA
    , CONVERT(VARCHAR(10), R.[ULTIMA ACAO], 103) ULTIMA_ACAO
    , FORMAT(R.[% SLA], 'P') SLA
    , R.MARCA
    , R.[SIGLA UNIDADE]
    , UPPER(R.PRODUCT) PRODUTO
    , UPPER(R.PROCESS) PROCESSO
    , UPPER(R.CLIENT) CLIENTE
FROM REQUESTIA_REQUESTS R
WHERE R.[CATEGORY] = 'Compras'
    AND R.[SITUACAO] = 'ABERTO' 
    AND (R.[RSTATUS] NOT LIKE '%Aguard%Aprov%')
    AND (R.[RSTATUS] NOT LIKE '%Aguard%Sol%')
    AND R.[TEMPO ULTIMA ACAO (H)] > 40
ORDER BY R.[ULTIMA ACAO] ASC