SELECT R.REQUEST CHAMADO
    , CONVERT(VARCHAR(10), R.ABERTURA, 103) ABERTURA
    , UPPER(R.CLIENT) SOLICITANTE
    , UPPER(R.RSTATUS) STATUS
    , CONVERT(VARCHAR(10), R.RESOLUCAO, 103) ENCERRAMENTO
    , UPPER(R.CURRANAL) ANALISTA
    , R.[UNIDADE ATENDIMENTO] UNIDADE
    , R.MARCA MARCA
    , R.[SIGLA UNIDADE] SIGLA
    , CONVERT(FLOAT, A1.QANSWER) ALIMENTACAO_DIA1
    , CONVERT(FLOAT, A2.QANSWER) ALIMENTACAO_DIA2
    , CONVERT(FLOAT, A3.QANSWER) ALIMENTACAO_DIA3
    , CONVERT(FLOAT, A4.QANSWER) ALIMENTACAO_DIA4
    , CONVERT(FLOAT, A5.QANSWER) ALIMENTACAO_DIA5
    , CONVERT(FLOAT, A6.QANSWER) ALIMENTACAO_DIA6
    , CONVERT(FLOAT, A7.QANSWER) ALIMENTACAO_DIA7
INTO dbo.RQE_TMP_ALIMENTACAO
FROM REQUESTIA_REQUESTS R
    LEFT JOIN REQUESTIA_QANSWER A1
        ON R.QSESSIONFORM = A1.QSESSION AND A1.QUESTION = 'CAP_Reembolso_Aliment1'
    LEFT JOIN REQUESTIA_QANSWER A2
        ON R.QSESSIONFORM = A2.QSESSION AND A2.QUESTION = 'CAP_Reembolso_Aliment2'
    LEFT JOIN REQUESTIA_QANSWER A3
        ON R.QSESSIONFORM = A3.QSESSION AND A3.QUESTION = 'CAP_Reembolso_Aliment3'
    LEFT JOIN REQUESTIA_QANSWER A4
        ON R.QSESSIONFORM = A4.QSESSION AND A4.QUESTION = 'CAP_Reembolso_Aliment4'
    LEFT JOIN REQUESTIA_QANSWER A5
        ON R.QSESSIONFORM = A5.QSESSION AND A5.QUESTION = 'CAP_Reembolso_Aliment5'
    LEFT JOIN REQUESTIA_QANSWER A6
        ON R.QSESSIONFORM = A6.QSESSION AND A6.QUESTION = 'CAP_Reembolso_Aliment6'
    LEFT JOIN REQUESTIA_QANSWER A7
        ON R.QSESSIONFORM = A7.QSESSION AND A7.QUESTION = 'CAP_Reembolso_Aliment7'
WHERE R.CATEGORY = 'Contas a Pagar'
    AND R.PRODUCT = 'Reembolso de Despesas'
    AND R.PROCESS = 'Adian Reembolso Despesas'
    AND R.RSTATUS NOT LIKE '%Cancel%'
    --AND R.REQUEST = 'CSI081454'
    AND R.ABERTURA >= '01/04/2019'

    LEFT JOIN REQUESTIA_QTABLEANSWER T1
        ON R.QSESSIONFORM = T1.QSESSION AND T1.TABLE_NAME = 'CONTAS_PGTO_PerioViag' AND T1.COLUMN_NAME = 'Periodo_Ida'
    LEFT JOIN REQUESTIA_QTABLEANSWER T2
        ON R.QSESSIONFORM = T2.QSESSION AND T2.TABLE_NAME = 'CONTAS_PGTO_PerioViag' AND T2.COLUMN_NAME = 'Periodo_Volta'

DROP TABLE dbo.RQE_TMP_ALIMENTACAO

SELECT *
FROM RQE_TMP_ALIMENTACAO
ORDER BY 1 DESC

SELECT R.QSESSIONFORM, * 
FROM REQUESTIA_REQUESTS R
WHERE R.REQUEST = 'CSI081454'
AND R.QSESSIONFORM = 162367;

SELECT *
FROM REQUESTIA_QANSWER A
WHERE A.QSESSION = 162367;


SELECT *
FROM REQUESTIA_QTABLEANSWER T
WHERE T.QSESSION = 162367;


SELECT R.[UNIDADE ATENDIMENTO], R.[SIGLA UNIDADE], COUNT(1)
FROM REQUESTIA_REQUESTS R
WHERE R.CATEGORY = 'Tecnologia da Informacao'
AND R.MARCA = 'DH'
AND R.CLOSED = 1
GROUP BY R.[UNIDADE ATENDIMENTO], R.[SIGLA UNIDADE]

SELECT *
FROM REQ_WKF_CAPEXNFD
WHERE ABERTURA <= CONVERT(VARCHAR(10), GETDATE()-7, 103)
ORDER BY 1 DESC
