-- ATUALIZA O EMAIL COMERCIAL A PARTIR DA MATRICULA DO FUNCIONAR

UPDATE P
SET P.EMACOM = 'anderson.santos@opty.com.br'
FROM R033PES P
    INNER JOIN R034FUN R
        ON P.CODPES = R.CODPES
WHERE R.NUMEMP = 6072

-- BUSCA TODOS OS FUNCIONARIOS
select
I.NOMCID AS City,
I.ESTCID AS COUNTRY,
UPPER(C.NOMCCU) AS Department,
R.NOMFUN AS DisplayName,
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 1) FIRST_MANE,
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 2) || ' ' ||
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 3) || ' ' ||
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 4) || ' ' ||
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 5) || ' ' ||
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 6) || ' ' ||
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 7) || ' ' ||
REGEXP_SUBSTR(R.NOMFUN, '[^ ]+', 1, 8) AS LAST_NAME,
P.NUMTEL AS MobilePhone,
P.NUMCEL AS PhoneNumber,
L.CODCEP AS PostalCode ,
I.CODEST AS STATE ,
L.ENDFIL AS StreetAddress,
UPPER(A.TITRED) AS Title,
'BR' AS UsageLocation,
P.EMACOM AS UserPrincipalName,
R.DATADM AS ADMISSIONDATE,

CASE WHEN S.DESSIT  <> 'Trabalhando' THEN R.DATAFA
ELSE NULL END AS RESIGNATIONDATE,

S.DESSIT as status,

L.RAZSOC as companyname,

p.emacom

from R034FUN R,
R030EMP E,
R018CCU C,
R033PES P,
R024CAR A,
R030FIL L,
R074CID I,
R010SIT S
WHERE R.NUMEMP = E.NUMEMP
AND R.SITAFA = S.CODSIT
AND R.CODCCU = C.CODCCU
AND R.NUMEMP = C.NUMEMP
AND R.CODPES = P.CODPES
AND R.CODCAR = A.CODCAR
AND R.ESTCAR = A.ESTCAR
AND R.NUMEMP = L.NUMEMP
AND R.CODFIL = L.CODFIL
AND L.CODCID = I.CODCID
AND E.NUMEMP NOT IN (1)
AND R.DATCCU = (SELECT MAX(X.DATCCU)FROM R034FUN X WHERE X.NUMCPF = R.NUMCPF)
GROUP BY I.ESTCID , E.NUMEMP, E.NOMEMP, R.NUMEMP, R.NOMFUN, UPPER(C.NOMCCU), P.NUMTEL, P.NUMCEL, UPPER(A.TITRED), L.CODCID, L.ENDFIL, I.NOMCID, L.CODCEP, I.CODEST, P.EMACOM, R.DATAFA, S.DESSIT, R.DATPOS, R.DATADM, L.RAZSOC
ORDER BY 18, 4, 5